export const FULL_MENU = [
  {
    label: 'Dashboard',
    image: 'assets/images/speedometer.png',
    items: [
      {
        label: 'Overview',
        icon: 'fas fa-th',
        image: 'assets/images/sidebar/sales.png',
        path: '/dashboard/overview',
        tooltip: 'View Dashboard Overview',
        show: true,
        canView: ['admin', 'super_admin', 'staff', 'user'],
      },
      // {
      //   label: 'AI Sales Prediction',
      //   icon: 'fas fa-chart-line',
      //   path: '/dashboard/ai-prediction',
      //   tooltip: 'AI Sales Prediction',
      //   canView: ['admin', 'super_admin'],
      // },
    ],
  },
  {
    label: 'Sales / POS',
    image: 'assets/images/sidebar/sales.png',
    items: [
      {
        label: 'New Bill / POS',
        icon: 'fas fa-file-alt',
        image: 'assets/images/sidebar/Billing.png',
        path: '/pos',
        tooltip: 'Billing POS',
        canView: ['admin', 'super_admin', 'staff', 'cashier'],
      },
      {
        label: 'Sales Invoices',
        icon: 'fas fa-history',
        image: 'assets/images/sidebar/sales-inv.png',
        path: '/dashboard/sales/history',
        tooltip: 'Sales Invoices',
        canView: ['admin', 'super_admin', 'staff'],
      },
      {
        label: 'Sales Items',
        icon: 'fas fa-shopping-cart',
        image: 'assets/images/sidebar/sales-item.png',
        path: '/dashboard/sales/items',
        tooltip: 'Sales Items',
        canView: ['admin', 'super_admin', 'staff'],
      },
      {
        label: 'Returns',
        icon: 'fas fa-undo',
        image: 'assets/images/sidebar/return.png',
        path: '/dashboard/sales/returns',
        tooltip: 'Manage Returns',
        canView: ['admin', 'super_admin', 'staff'],
      },
    ],
  },
  {
    label: 'Purchase',
    image: 'assets/images/sidebar/purchase.png',
    items: [
      {
        label: 'Purchase Invoices',
        icon: 'fas fa-box',
        image: 'assets/images/sidebar/invoice.png',
        path: '/dashboard/purchase/purchase-invoices',
        tooltip: 'View Purchase Invoices',
        canView: ['admin', 'super_admin', 'staff'],
      },
      {
        label: 'Create Purchase Invoice',
        icon: 'fas fa-file-alt',
        image: 'assets/images/sidebar/create-new.png',
        path: '/dashboard/purchase/create-purchase-invoice',
        tooltip: 'Create Purchase Invoice',
        canView: ['admin', 'super_admin'],
      },
      {
        label: 'Purchase Return',
        icon: 'fas fa-file-alt',
        image: 'assets/images/sidebar/return.png',
        path: '/dashboard/purchase/purchase-invoice-return-items',
        tooltip: 'Purchase Invoice Return Items',
        canView: ['admin', 'super_admin'],
      },
      {
        label: 'Wanted Book',
        icon: 'fas fa-book',
        image: 'assets/images/sidebar/pur-order.png',
        path: '/dashboard/purchase/wanted-book',
        tooltip: 'Track customer requested items',
        canView: ['admin', 'super_admin', 'staff', 'cashier', 'user'],
      },
    ],
  },
  {
    label: 'Orders Management',
    image: 'assets/images/sidebar/pur-order.png',
    items: [
      {
        label: 'Purchase Orders',
        icon: 'fas fa-plus-square',
        image: 'assets/images/sidebar/pur-order.png',
        path: '/dashboard/purchase/purchase-orders',
        tooltip: 'View Purchase Orders',
        canView: ['admin', 'super_admin', 'staff'],
      },
      {
        label: 'Create Purchase Order',
        icon: 'fas fa-file-alt',
        image: 'assets/images/sidebar/create.png',
        path: '/dashboard/purchase/purchase-order',
        tooltip: 'Create Purchase Order',
        canView: ['admin', 'super_admin'],
      },
    ],
  },

  {
    label: 'Inventory',
    image: 'assets/images/sidebar/inventory.png',
    items: [
      {
        label: 'Stock List',
        icon: 'fas fa-exclamation-circle',
        image: 'assets/images/sidebar/stock-list.png',
        path: '/dashboard/inventory/stock-list',
        tooltip: 'View Stock Levels',
        canView: ['admin', 'super_admin', 'staff'],
      },
      {
        label: 'Low Stock',
        icon: 'fas fa-clock',
        image: 'assets/images/sidebar/low-stock.png',
        path: '/dashboard/inventory/low-stock',
        tooltip: 'Low Stock Items',
        canView: ['admin', 'super_admin', 'staff'],
      },
      {
        label: 'Re-order',
        icon: 'fas fa-sync-alt',
        image: 'assets/images/sidebar/re-order.png',
        path: '/dashboard/inventory/re-order',
        tooltip: 'Re-order Products',
        canView: ['admin', 'super_admin', 'staff'],
      },
      {
        label: 'Expired Stocks',
        icon: 'fas fa-calendar-times',
        image: 'assets/images/sidebar/expired-stock.png',
        path: '/dashboard/inventory/expired-stocks',
        tooltip: 'Expired Product List',
        canView: ['admin', 'super_admin', 'staff'],
      },
      {
        label: 'Non Moving Stocks',
        icon: 'fas fa-box-open',
        image: 'assets/images/sidebar/inventory.png',
        path: '/dashboard/inventory/non-moving',
        tooltip: 'View Non Moving Stocks',
        canView: ['admin', 'super_admin', 'staff'],
      },
      {
        label: 'Stock Adjustment',
        icon: 'fas fa-check-square',
        image: 'assets/images/sidebar/inventory.png',
        path: '/dashboard/inventory/stock-adjustment',
        tooltip: 'Adjust Stock Levels',
        canView: ['admin', 'super_admin'],
      },
      {
        label: 'Expired Stocks',
        icon: 'fas fa-check-square',
        image: 'assets/images/sidebar/stock-batch.png',
        path: '/dashboard/inventory/expired-stocks',
        tooltip: 'Expired stock batches',
        canView: ['admin', 'super_admin', 'staff'],
      },
    ],
  },

  {
    label: 'Products',
    image: 'assets/images/sidebar/products.png',
    items: [
      {
        label: 'Product List',
        icon: 'fas fa-box',
        image: 'assets/images/sidebar/pro-list.png',
        path: '/dashboard/products',
        tooltip: 'Product List',
        canView: ['admin', 'super_admin', 'staff'],
      },
      {
        label: 'Add New Product',
        icon: 'fas fa-plus-square',
        image: 'assets/images/sidebar/add nev.png',
        path: '/dashboard/products/add-new-product',
        tooltip: 'Add Product',
        canView: ['admin', 'super_admin'],
      },

      {
        label: 'Categories List',
        icon: 'fas fa-plus-square',
        image: 'assets/images/sidebar/categories.png',
        path: '/dashboard/categories/all-categories',
        tooltip: 'Product Categories',
        canView: ['admin', 'super_admin'],
      },
      {
        label: 'Medicine Groups',
        icon: 'fas fa-layer-group',
        image: 'assets/images/sidebar/stock-list.png', // Reusing stock list icon or similar
        path: '/dashboard/medicine-group/all-groups',
        tooltip: 'Manage Medicine Groups',
        canView: ['admin', 'super_admin', 'staff'],
      },

      // {
      //   label: 'Import/Export Products',
      //   icon: 'fas fa-file-alt',
      //   path: '/dashboard/products/import-export',
      //   tooltip: 'Import/Export Products',
      //   canView: ['admin', 'super_admin'],
      // },
      // {
      //   label: 'Categories',
      //   icon: 'fas fa-plus-square',
      //   path: '/dashboard/products/category',
      //   tooltip: 'Product Categories',
      //   canView: ['admin', 'super_admin'],
      // },
    ],
  },
  {
    label: 'Finance',
    image: 'assets/images/sidebar/finance.png',
    items: [
      {
        label: 'Expenses',
        icon: 'fas fa-exclamation-circle',
        image: 'assets/images/sidebar/expense.png',
        path: '/dashboard/finance/expenses',
        tooltip: 'View Expenses',
        canView: ['admin', 'super_admin', 'staff'],
      },
      // {
      //   label: 'Cash sessions',
      //   icon: 'fas fa-clock',
      //   image: 'assets/images/sidebar/cash.png',
      //   path: '/dashboard/finance/cash-sessions',
      //   tooltip: 'Cash Sessions',
      //   canView: ['admin', 'super_admin', 'staff'],
      // },
      {
        label: 'Cash transactions',
        icon: 'fas fa-sync-alt',
        image: 'assets/images/sidebar/cash-tranc.png',
        path: '/dashboard/finance/cash-transactions',
        tooltip: 'Cash Transactions',
        canView: ['admin', 'super_admin', 'staff'],
      },
    ],
  },

  {
    label: 'Reports',
    image: 'assets/images/sidebar/report.png',
    items: [
      {
        label: 'Sales Reports',
        icon: 'fas fa-file-alt',
        image: 'assets/images/sidebar/sales-report.png',
        path: '/dashboard/report/sales',
        tooltip: 'Sales Reports',
        canView: ['admin', 'super_admin', 'staff'],
      },
      {
        label: 'Stock Reports',
        icon: 'fas fa-file-alt',
        image: 'assets/images/sidebar/sales-report.png',
        path: '/dashboard/report/stock',
        tooltip: 'Stock Reports',
        canView: ['admin', 'super_admin', 'staff'],
      },
      {
        label: 'Purchase Reports',
        icon: 'fas fa-file-alt',
        image: 'assets/images/sidebar/sales-report.png',
        path: '/dashboard/report/purchase',
        tooltip: 'Purchase Reports',
        canView: ['admin', 'super_admin'],
      },
      {
        label: 'Expense Reports',
        icon: 'fas fa-file-alt',
        image: 'assets/images/sidebar/sales-report.png',
        path: '/dashboard/report/expense',
        tooltip: 'Expense Reports',
        canView: ['admin', 'super_admin'],
      },
    ],
  },
  {
    label: 'GST & TAX',
    image: 'assets/images/sidebar/tax.png',
    items: [
      {
        label: 'GST Reports',
        icon: 'fas fa-file-alt',
        image: 'assets/images/sidebar/tax-report.png',
        path: '/dashboard/gst-info/gst-reports',
        tooltip: 'GST Reports',
        canView: ['admin', 'super_admin', 'staff'],
      },
      {
        label: 'View GST Reports',
        icon: 'fas fa-file-alt',
        image: 'assets/images/sidebar/tax-report.png',
        path: '/dashboard/gst-info/view',
        tooltip: 'View GST Reports',
        canView: ['admin', 'super_admin', 'staff'],
      },
    ],
  },
  {
    label: 'Supplier',
    image: 'assets/images/sidebar/supplier.png',
    items: [
      {
        label: 'All Suppliers',
        icon: 'fas fa-truck',
        image: 'assets/images/sidebar/sup-new.png',
        path: '/dashboard/supplier',
        tooltip: 'All Suppliers',
        canView: ['admin', 'super_admin', 'staff'],
      },
      {
        label: 'Add New Supplier',
        icon: 'fas fa-plus-square',
        image: 'assets/images/sidebar/add-user.png',
        path: '/dashboard/supplier/add',
        tooltip: 'Add Supplier',
        canView: ['admin', 'super_admin'],
      },
      {
        label: 'Supplier Invoices',
        icon: 'fas fa-file-alt',
        image: 'assets/images/sidebar/inv-new.png',
        path: '/dashboard/supplier/supplier-inv',
        tooltip: 'Supplier Invoices',
        canView: ['admin', 'super_admin'],
      },
      {
        label: 'Supplier Payments',
        icon: 'fas fa-money-bill-alt',
        image: 'assets/images/sidebar/pos-pay.png',
        path: '/dashboard/supplier/payments',
        tooltip: 'View Supplier Pending Payments',
        canView: ['admin', 'super_admin', 'staff'],
      },
    ],
  },
  {
    label: 'Customer',
    image: 'assets/images/sidebar/customer.png',
    items: [
      {
        label: 'Customer Profiles',
        icon: 'fas fa-id-card',
        image: 'assets/images/sidebar/customer-new.png',
        path: '/dashboard/customer/profiles',
        tooltip: 'View customer profiles',
        canView: ['admin', 'super_admin', 'staff'],
      },
      {
        label: 'Loyalty Points',
        icon: 'fas fa-user-plus',
        image: 'assets/images/sidebar/loyel.png',
        path: '/dashboard/customer/loyalty-points',
        tooltip: 'Manage Loyalty Points',
        canView: ['admin', 'super_admin', 'staff'],
      },
      // {
      //   label: 'Customer Feedback',
      //   icon: 'fas fa-comment-dots',
      //   image: 'assets/images/sidebar/inv-new.png',
      //   path: '/dashboard/customer/feedback',
      //   tooltip: 'View Customer Feedback',
      //   canView: ['admin', 'super_admin', 'staff'],
      // },
    ],
  },
  {
    label: 'Doctor',
    image: 'assets/images/sidebar/doctor.png',
    items: [
      {
        label: 'Doctor Profiles',
        icon: 'fas fa-user-md',
        image: 'assets/images/sidebar/doctor-new.png',
        path: '/dashboard/doctor/all-doctors',
        tooltip: 'View doctor profiles',
        canView: ['admin', 'super_admin', 'staff'],
      },
      {
        label: 'Add New Doctor',
        icon: 'fas fa-plus-square',
        image: 'assets/images/sidebar/add-user.png',
        path: '/dashboard/doctor/add-new-doctor',
        tooltip: 'Add new doctor',
        canView: ['admin', 'super_admin'],
      },
      // {
      //   label: 'Doctor Reports',
      //   icon: 'fas fa-file-alt',
      //   image: 'assets/images/sidebar/sales-report.png',
      //   path: '/dashboard/doctor/doctor-reports',
      //   tooltip: 'View doctor reports',
      //   canView: ['admin', 'super_admin', 'staff'],
      // },
    ],
  },
  {
    label: 'Human Resources',
    image: 'assets/images/sidebar/hr.png',
    items: [
      {
        label: 'Employees',
        icon: 'fas fa-users',
        image: 'assets/images/sidebar/staff.png',
        path: '/dashboard/hr-management/all-employees',
        tooltip: 'Manage Employees',
        canView: ['admin', 'super_admin'],
      },

      {
        label: 'Shift Management',
        icon: 'fas fa-user-plus',
        image: 'assets/images/sidebar/changes.png',
        path: '/dashboard/hr-management/shift-sessions',
        tooltip: 'Manage Employee Shifts',
        canView: ['admin', 'super_admin'],
      },

      {
        label: 'Employee Attendance',
        icon: 'fas fa-users-cog',
        image: 'assets/images/sidebar/immigration.png',
        path: '/dashboard/hr-management/all-attendance',
        tooltip: 'Manage Employee Attendance',
        canView: ['admin', 'super_admin'],
      },

      {
        label: 'Employee Leave',
        icon: 'fas fa-print',
        image: 'assets/images/sidebar/leave-new.png',
        path: '/dashboard/hr-management/employee-leave',
        tooltip: 'Employee Leave Management',
        canView: ['admin', 'super_admin'],
      },

      {
        label: 'Employee Payroll',
        icon: 'fas fa-money-check-alt',
        image: 'assets/images/sidebar/calendars.png',
        path: '/dashboard/hr-management/employee-payroll',
        tooltip: 'Manage Employee Payroll',
        canView: ['admin', 'super_admin'],
      },
    ],
  },
  {
    label: 'User & Role Management',
    image: 'assets/images/sidebar/roles.png',
    items: [
      {
        label: 'Roles',
        icon: 'fas fa-shield-alt',
        image: 'assets/images/sidebar/project-plan.png',
        path: '/dashboard/user-role-management/roles',
        tooltip: 'Manage Roles',
        canView: ['admin', 'super_admin'],
      },
      {
        label: 'Users',
        icon: 'fas fa-users',
        image: 'assets/images/sidebar/profiles.png',
        path: '/dashboard/user-role-management/users',
        tooltip: 'Manage Users',
        canView: ['admin', 'super_admin'],
      },
      {
        label: 'Permissions',
        icon: 'fas fa-lock',
        image: 'assets/images/sidebar/permission.png',
        path: '/dashboard/user-role-management/permissions',
        tooltip: 'Manage Permissions',
        canView: ['admin', 'super_admin'],
      },
      {
        label: 'Role Assignment',
        icon: 'fas fa-check-square',
        image: 'assets/images/sidebar/assign.png',
        path: '/dashboard/user-role-management/role-permission',
        tooltip: 'Assign Roles',
        canView: ['admin', 'super_admin'],
      },
    ],
  },

  {
    label: 'Settings & Configurations',
    image: 'assets/images/sidebar/settings.png',
    items: [
      {
        label: 'Shops',
        icon: 'fas fa-box',
        image: 'assets/images/sidebar/shop.png',
        path: '/dashboard/settings/shops',
        tooltip: 'Shops Management',
        canView: ['admin', 'super_admin'],
      },
      {
        label: 'Terminals',
        icon: 'fas fa-box',
        image: 'assets/images/sidebar/terminal.png',
        path: '/dashboard/settings/terminals',
        tooltip: 'Terminals Management',
        canView: ['admin', 'super_admin'],
      },
      {
        label: 'My Profile',
        icon: 'fas fa-users-cog',
        image: 'assets/images/sidebar/settings.png',
        path: '/dashboard/profile/my-profile',
        tooltip: 'My Profile',
        canView: ['admin', 'super_admin'],
      },

      // {
      //   label: 'Backup & Restore',
      //   icon: 'fas fa-database',
      //   path: '/dashboard/settings/backup-restore',
      //   tooltip: 'Backup & Restore',
      //   canView: ['admin', 'super_admin'],
      // },
    ],
  },

  {
    label: 'Support & Help',
    image: 'assets/images/sidebar/support.png',
    items: [
      {
        label: 'Help Center',
        icon: 'fas fa-question-circle',
        image: 'assets/images/sidebar/faq.png',
        path: '/dashboard/support-help/help-center',
        tooltip: 'Help Center',
        canView: ['admin', 'super_admin', 'staff'],
      },
      {
        label: 'Contact Support',
        icon: 'fas fa-envelope',
        image: 'assets/images/sidebar/help-desk.png',
        path: '/dashboard/support-help/contact-support',
        tooltip: 'Contact Support',
        canView: ['admin', 'super_admin', 'staff'],
      },
    ],
  },
];
